# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.064},
    {id: 1, size: 0.064},
    # {id: 2, size: 0.1277},
    # {id: 3, size: 0.1277},
    {id: 4, size: 0.075}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]

# {id: 0, size: 0.1277, x: 0.284, y: 0.157, qw: 0.7071068, qz: -0.7071068},
# {id: 1, size: 0.1277, x: 0.284, y: -0.284, qw: 0.7071068, qz: -0.7071068},
# {id: 2, size: 0.1277, x: -0.157, y: -0.284, qw: 0.7071068, qz: -0.7071068},
# {id: 3, size: 0.1277, x: -0.157, y: 0.157, qw: 0.7071068, qz: -0.7071068}
    
# {id: 0, size: 0.1277, x: 0.2203, y: 0.2203, qw: 0.7071068, qz: -0.7071068},
# {id: 1, size: 0.1277, x: 0.2203, y: -0.2203, qw: 0.7071068, qz: -0.7071068},
# {id: 2, size: 0.1277, x: -0.2203, y: -0.2203, qw: 0.7071068, qz: -0.7071068},
# {id: 3, size: 0.1277, x: -0.2203, y: 0.2203, qw: 0.7071068, qz: -0.7071068}

## Calibrated via matlab
# {id: 0, size: 0.13, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
# {id: 1, size: 0.13, x: -0.4580, y: 0.0353, z: 0.0927, qw: 0.9983, qx: 0.0382, qy: 0.0400, qz: -0.0182},
# {id: 3, size: 0.13, x: 0.0028, y: 0.4360, z: -0.0421, qw: 0.9948, qx: 0.0471, qy: -0.0897, qz: 0.0014},
# {id: 2, size: 0.13, x: -0.4527, y: 0.4571, z: 0.0312, qw: 0.9721, qx: -0.2280, qy: 0.0552, qz: -0.0007}

# Try me next - using 0 as master. Hopefully keeping them on a plane will help with the standalones?
# {id: 0, size: 0.1273, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
# {id: 1, size: 0.1273, x: -0.4408, y: 0.0, z: 0.0},
# {id: 3, size: 0.1273, x: -0.4408, y: 0.4408, z: 0.0},
# {id: 2, size: 0.1273, x: 0.0, y: 0.4408, z: 0.0}  


tag_bundles:
  [
    
  ]
