arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin # turtlebot_arm_arm_kinematics/IKFastKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.05
  kinematics_solver_timeout: 0.2
  kinematics_solver_attempts: 5
  # optional parameters for caching:
  max_cache_size: 10000
  min_pose_distance: 0.01
  min_joint_config_distance: 4
  position_only_ik: True
